apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"web-app","namespace":"dev","creationTimestamp":null,"labels":{"app":"web-app"}},"spec":{"replicas":6,"selector":{"matchLabels":{"app":"web-app"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"web-app"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17.8-alpine","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
  namespace: dev
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: nginx:1.23.1-alpine
        name: nginx
        resources: {}
status: {}

