apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ckad
  annotations:
    volume.kubernetes.io/selected-node: kind-control-plane
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sc1

