kind: Service
apiVersion: v1
metadata:
  name: public-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: customer-app
    track: canary
  ports:
    - port: 80
      targetPort: 80

