apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp-pod
  name: temp-pod
spec:
  containers:
  - image: alpine
    name: temp-pod
    resources: {}
    command: ["sleep", "60000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

