apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: check-db
        image: postgres:9.6.5
        command: ['sh', '-c',
          'until pg_isready -h db -p 5432;
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: backend
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:testPassword@db:5432/db"
        image: localhost:5001/pluralsight_backend:latest
        readinessProbe:
          httpGet:
            path: /api/v1/
            port: api
        livenessProbe:
          httpGet:
            path: /api/v1/
            port: api
        ports:
        - name: api
          containerPort: 8000
      - name: db-admin
        image: adminer
        ports:
          - containerPort: 8080

