apiVersion: v1
kind: Pod
metadata:
  name: custom-metrics-collector
spec:
  restartPolicy: Never
  serviceAccountName: custom-metrics
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: custom-metrics-role
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: custom-metrics
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: custom-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics
subjects:
- kind: ServiceAccount
  name: custom-metrics
  namespace: deployments
