apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-manager
  template:
    metadata:
      labels:
        app: deploy-manager
    spec:
      serviceAccountName: deploy-manager
      containers:
      - name: busybox
        image: busybox:stable
        command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: deploy-manager
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deploy-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-manager-role
subjects:
- kind: ServiceAccount
  name: deploy-manager
  namespace: deployments
