apiVersion: v1
kind: Pod
metadata:
  name: ps-api
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo $WEATHER_API; echo $STORMWARN_API']
    env:
    - name: WEATHER_API
      value: https://weather.pluralsight.com/v2
    - name: STORMWARN_API
      value: https://swarn.pluralsight.com/v1
