apiVersion: v1
kind: Pod
metadata:
  name: big-pod
  namespace: ps-sandbox
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    resources:
      requests:
        cpu: "2"
        memory: "64Mi"
      limits:
        cpu: "100"
        memory: "64Gi"
